class Autogenerated {
  int? code;
  String? status;
  Data? data;

  Autogenerated({this.code, this.status, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    status = json['status'];
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['code'] = code;
    data['status'] = status;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  List<HouseRange>? houseRange;
  List<RoomNum>? roomNum;
  List<HouseArea>? houseArea;

  Data({this.houseRange, this.roomNum, this.houseArea});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['houseRange'] != null) {
      houseRange = <HouseRange>[];
      json['houseRange'].forEach((v) {
        houseRange!.add(new HouseRange.fromJson(v));
      });
    }
    if (json['roomNum'] != null) {
      roomNum = <RoomNum>[];
      json['roomNum'].forEach((v) {
        roomNum!.add(RoomNum.fromJson(v));
      });
    }
    if (json['houseArea'] != null) {
      houseArea = <HouseArea>[];
      json['houseArea'].forEach((v) {
        houseArea!.add(HouseArea.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (houseRange != null) {
      data['houseRange'] = houseRange!.map((v) => v.toJson()).toList();
    }
    if (roomNum != null) {
      data['roomNum'] = roomNum!.map((v) => v.toJson()).toList();
    }
    if (houseArea != null) {
      data['houseArea'] = houseArea!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class HouseRange {
  int? code;
  String? name;

  HouseRange({this.code, this.name});

  HouseRange.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['code'] = code;
    data['name'] = name;
    return data;
  }
}
class RoomNum {
  int? code;
  String? name;

  RoomNum({this.code, this.name});

  RoomNum.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['code'] = code;
    data['name'] = name;
    return data;
  }
}
class HouseArea {
  int? code;
  String? name;

  HouseArea({this.code, this.name});

  HouseArea.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['code'] = code;
    data['name'] = name;
    return data;
  }
}